name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  erlang_test:
    name: OTP ${{ matrix.otp }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        otp: [27, 28, '29.0-rc1']

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Erlang/OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
        rebar3-version: '3.26.0'

    - name: Restore Dependencies Cache
      uses: actions/cache@v4
      with:
        path: _build
        key: ${{ runner.os }}-otp-${{ matrix.otp }}-rebar3-${{ hashFiles('rebar.config') }}
        restore-keys: |
          ${{ runner.os }}-otp-${{ matrix.otp }}-rebar3-

    - run: rebar3 eunit
  dialyzer:
    name: Dialyzer (OTP 28)
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Erlang/OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: '28'
        rebar3-version: '3.26.0'

    - name: Restore Dialyzer PLT Cache
      uses: actions/cache@v4
      with:
        path: |
          _build/default/rebar3_28_plt
          ~/.cache/rebar3/rebar3_28_plt
        key: ${{ runner.os }}-otp-28-dialyzer-${{ hashFiles('rebar.config') }}
        restore-keys: |
          ${{ runner.os }}-otp-28-dialyzer-

    - run: rebar3 dialyzer
  elixir_test:
    name: Elixir ${{ matrix.elixir }} (OTP 28)
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ci/uuidv8_test_ex

    strategy:
      fail-fast: false
      matrix:
        elixir: ['1.18', '1.19', 'v1.20.0-rc.0']

    steps:
    - uses: actions/checkout@v4

    - name: Setup Elixir/OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: '28'
        elixir-version: ${{ matrix.elixir }}

    - run: mix deps.get
    - run: mix test --warnings-as-errors